export const SEARCH_STOCKS = 'SEARCH_STOCKS';
export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_STOCKS = 'CLEAR_STOCKS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_COMPANY_NEWS = 'GET_COMPANY_NEWS';
export const SET_LOADING = 'SET_LOADING';
export const SHOW_RESULT= 'SHOW_RESULT';
export const REMOVE_RESULT = 'REMOVE_RESULT';
export const GET_EARNINGS = 'GET_EARNINGS';
export const CLEAR_EARNING = 'CLEAR_EARNING';

